### ISSUE TITLE
there is no reference to angularjs in /resources/calories-tracker.html

### ISSUE THREAD

**Issue by mlotfi2005** [jhades/spring-mvc-angularjs-sample-app#4]
HI,

I downloaded this project and install it in eclipse, I did not see any reference to angular.js in calories-tracker.html.

**Comment by jhades** [comment]
This is normal, in the main file calories-tracker.html there is only reference to the [requirejs](http://requirejs.org/) boostrap script. This will then lazy load angular and other dependencies.

**Comment by zygimantus** [comment]
I will jus add that the reference to any file is wrong. It should be not etc., href="/resources/bower_components/pure/pure.css but href="/calories-tracker/resources/bower_components/pure/pure.css
