### ISSUE TITLE
Not able to login, console stuck at Starting ProtocolHandler ["http-bio-8443"]

### ISSUE THREAD

**Issue by alchemistgo87** [jhades/spring-mvc-angularjs-sample-app#5]

**Comment by jhades** [comment]
I just built now the application following the README in a clean checkout from the command line and launched it,  HTTPS is working OK as I can login to the app. How was the app build, are there any more error messages in the console? Im closing as this is not actionable

**Comment by bel-dbo** [comment]
Hi,

I had the same issue, but realized the the bower components had not been properly downloaded.
Firewall prevented the installation.

Solved after I read this:
http://stackoverflow.com/questions/21789683/how-to-fix-bower-ecmderr

HTH

**Comment by cmorettiasu** [comment]
Having this exact same issue when I follow the listed instructions.  I can make it through the bower install with no issues, but when I go to run it in 'test' mode, it gives a bunch of stack traces about "No qualifying bean of type [javax.persistence.EntityManager]" and then sits idle at the ProtocalHandler.
