### ISSUE TITLE
Unable to compile the project

### ISSUE THREAD

**Issue by ghost** [jhades/spring-mvc-angularjs-sample-app#6]
Hi,
I am not able to compile the project after installing the bower_components. Could you please help me ?

`Errors occurred during the build.
Errors running builder 'JavaScript Validator' on project 'calories-tracker'.
java.lang.NullPointerException`

**Comment by jhades** [comment]
I just did a clean checkout and build using the commands in the README, and the project still works OK. How are you building the project? Im closing the issue as its not actionable, I propose starting from a clean install and reapplying the commands on the README and test the application before importing it to an IDE, to make sure eveything works OK from the command line first.
